/**
 * Moving Goods Microservices
 * FSM - Moving Goods Core Microservice - Delivery Service
 *
 * OpenAPI spec version: 0.0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class DeliveryRequest (
  partnerId: Option[Int] = None,
  pickUpLocation: Option[AddressRequest] = None,
  dropOffLocation: Option[AddressRequest] = None
) extends ApiModel


