/**
 * Moving Goods Delivery API
 * Moving Goods Delivery Management API
 *
 * OpenAPI spec version: 0.0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class LatLong (
  latitude: Option[Double] = None,
  longitude: Option[Double] = None
) extends ApiModel


